### ISSUE TITLE
Cannot download move2kuve

### ISSUE THREAD

**Issue by remyleone** [konveyor/homebrew-move2kube#38]
**Describe the bug**

**To Reproduce**

```
$ brew upgrade
Running `brew update --preinstall`...
==> Upgrading 1 outdated package:
konveyor/move2kube/move2kube 0.2.0 -> 0.3.0
==> Downloading https://github.com/konveyor/homebrew-move2kube/releases/download/v0.3.0/move2kube-0.3.0.big_sur.bottle.tar.gz
curl: (22) The requested URL returned error: 404

Error: move2kube: Failed to download resource "move2kube"
Download failed: https://github.com/konveyor/homebrew-move2kube/releases/download/v0.3.0/move2kube-0.3.0.big_sur.bottle.tar.gz
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ashokponkumar** [comment]
@HarikrishnanBalagopal `v` seems to be missing in the asset names in https://github.com/konveyor/homebrew-move2kube/releases/tag/v0.3.0 . Please take a look.

Thanks @remyleone for the filing the bug. We will fix the bug shortly, in the meanwhile, you can either use the curl based method or download it directly from the releases 

`bash <(curl https://raw.githubusercontent.com/konveyor/move2kube/main/scripts/install.sh)`

`https://github.com/konveyor/move2kube/releases/tag/v0.3.0`

https://move2kube.konveyor.io/installation/cli

**Comment by remyleone** [comment]
I can wait for the new version :)

**Comment by ashokponkumar** [comment]
> I can wait for the new version :)

sure :)

**Comment by HarikrishnanBalagopal** [comment]
@remyleone Please try `brew upgrade` again, I have fixed the stable formula.
Testing it in WSL Ubuntu 20.04 on my Windows laptop `brew upgrade` from version `0.2.0` to `0.3.0` seems to be working now.

```
$ move2kube version -l
version: v0.2.0
gitCommit: 8a4e2b89f0908e08fa817467bf4cecfcb9649cc9
gitTreeState: clean
goVersion: go1.16.9
$ brew upgrade
Running `brew update --preinstall`...
==> Upgrading 1 outdated package:
konveyor/move2kube/move2kube 0.2.0 -> 0.3.0
==> Downloading https://github.com/konveyor/homebrew-move2kube/releases/download/v0.3.0/move2kube-0.3.0.x86_64_linux.bottle.tar.gz
Already downloaded: /home/user/.cache/Homebrew/downloads/f4962695976802e80f55eaf3387dc95cdaf080778b9d50320410dac3af417ed8--move2kube-0.3.0.x86_64_linux.bottle.tar.gz
==> Upgrading konveyor/move2kube/move2kube
  0.2.0 -> 0.3.0

==> Pouring move2kube-0.3.0.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/move2kube/0.3.0: 5 files, 17.5MB
==> Running `brew cleanup move2kube`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /home/linuxbrew/.linuxbrew/Cellar/move2kube/0.2.0... (5 files, 15.5MB)
$ move2kube version -l
version: v0.3.0
gitCommit: 842d8ff3953ca517f085cbc6f26b8f25db94115f
gitTreeState: clean
goVersion: go1.17.6
```
